ibexa/gh-workflows

.github/workflows/browser-tests.yml
JIRA: https://issues.ibexa.co/browse/IBX-1290
This PR introduces a Github Actions workflow that runs Browser tests that have been run so far on Travis.
Example usages:
https://github.com/ezsystems/ezplatform-admin-ui/pull/1999 (basic one)
https://github.com/ibexa/oss/pull/22 (more complex)
So far Slack notifications look like this:
and they will be posted to a special Slack channel for every workflow run that is not triggered by a PR (cron, manual, push). I think it's a good start and we can finetune it if needed.
I've split the workflow into two jobs:
1) One that sets up and runs the tests
2) One that sends notifications to Slack (that's always executed)
I think it's easier than doing it in a single job, because we don't have to worry about the job quitting too early and skipping the …
=> Added workflow running browser tests

.github/workflows/browser-tests.yml
Things done:
1) Removed the `composer install` step performed inside each package
Current solution relied on Composer vendor binaries to deliver the script - it was done this way to limit the amount of logic in each Travis configuration file. With Github Actions we can do it differently, recipes-style and download the needed file directly.
Companion PR that changes the scripts directory structure: https://github.com/ibexa/ci-scripts/pull/31
2) Added Composer dependencies caching
I've decided to define the COMPOSER_CACHE_DIR, because relying on default values is tricky - currently it changes in the middle of job execution.
Current behaviour:
1. Job starts: the cache directory is in `/home/runner/.cache/composer`
2. Project is fully set up: the cache directory is in …
=> [Browser tests] Added composer cache and removed the composer install step for each package

.github/workflows/browser-tests.yml
This PR allows us to test changes to the ci-scripts repository (for example: https://github.com/ibexa/ci-scripts/pull/37)
by setting the `ci-scripts-branch` argument. It should be much easier than the current way of doing it.
Example usage:
https://github.com/ezsystems/BehatBundle/pull/260/files#diff-0d1742b44d1a1285f5590138b778e9a2a6dc73055a7cf4ee1741f4ca706664a0R19
(testing https://github.com/ibexa/ci-scripts/pull/37 )
=> Added a way of selecting ci-scripts branch

.github/workflows/browser-tests.yml
Adds tests running with compatibility-layer enabled.
All the code is rebranded, so there's not a lot this layer has to do, but at least we check:
1) that the routing for correct edition is applied
2) that the recipes content (including the Kernel class) is stil relevant
Companion PRs:
https://github.com/ibexa/oss/pull/36
https://github.com/ibexa/content/pull/28
https://github.com/ibexa/experience/pull/21
https://github.com/ibexa/commerce/pull/32
Steps were taken from:
https://doc.ibexa.co/en/master/updating/from_3.3/to_4.0/#add-compatibility-layer-package
=> Added compatibility layer setup to browser tests

.github/workflows/browser-tests.yml
Part of BehatBundle rebranding: https://issues.ibexa.co/browse/IBX-2322
After BehatBundle rebranding we would have to add IFs here, because the path of the script is `vendor/ezsystems/behatbundle...` on v3.3 and `vendor/ibexa/behat...` on v4.
I think moving it to this file is a cleaner option.
=> [Browser tests] Moved multirepository setup to the workflow

.github/workflows/browser-tests.yml
Needed to unblock CI in https://github.com/ezsystems/ezplatform-http-cache/pull/172 and merge it
You can see in https://github.com/ezsystems/ezplatform-http-cache/actions/workflows/browser-tests.yaml that the HTTP cache tests have not been really stable - a lot of the jobs fail with:
```
And response headers contain                                                         # Ibexa\Behat\Browser\Context\BrowserContext::responseHeadersContain()
| Header  | Value |
| X-Cache | HIT   |
Examples:
| embeddingItemName  | embeddedItemName  |
| EmbeddingItemNoEsi | EmbeddedItemNoEsi |
Failed asserting that 0.089 is greater than '5'.
| EmbeddingItemEsi   | EmbeddedItemEsi   |
Failed asserting that 0.0867 is greater than '5'.
```
I've found that it's caused by not clearing the cache after the config …
=> [Behat] Added clearing cache after every setup phase

.github/workflows/browser-tests.yml
Refactored Slack notifications.
The new format looks as below:
The notifications are now part of the same job as tests, meaning that we will no longer have the skipped "Send notification" job in Pull Requests (which were confusing).
=> Refactored notifications into a single job and reformatted message

.github/workflows/browser-tests.yml
JIRA: https://issues.ibexa.co/browse/IBX-2802
Example build with jobs divided into 1,2 and 3 groups:
https://github.com/ezsystems/BehatBundle/actions/runs/2172555366
I've decided to enable this feature only for non-PR builds - PR builds will always use 1 job. This will allow us to assess this approach and we will finetune it in the future if needed.
For 2 jobs the matrix looks like this:
```
{
"offset": [
0,
1
]
}
```
And the offset is then used to pick the right group of tests.
I reworked the notifications to include the job number in them, the result now looks like this:
I haven't found a way how to include the workflow name in them.
=> IBX-2802: Add the posibility to split browser tests into multiple jobs

.github/workflows/browser-tests.yml
Tested in https://github.com/ibexa/commerce/pull/105
Right now our regression PRs do not run all of the tests, but only a subset.
You can see that the first build (https://github.com/ibexa/commerce/runs/7193861471?check_suite_focus=true) runs only 19 Scenarios, but the second one (with the fix included) runs all 57:
https://github.com/ibexa/commerce/runs/7194411154?check_suite_focus=true
For PRs we manually reduce the number of jobs to 1 - we should no longer rely on the inputs.job-count value.
=> [Browser tests] Fixed PR builds running only a subset of tests

.github/workflows/browser-tests.yml
This is a standalone PR that will allow us to omit success Slack notifications on demand.
=> [Browser tests] Added a posibility to skip success Slack notifications

.github/workflows/browser-tests.yml
https://github.com/ibexa/docker/pull/7/files adds a `varnish7` file that should be detected as Varnish setup as well.
Tested in https://github.com/ezsystems/ezplatform-http-cache/pull/175
=> [Browser tests] Expanded the setups when Varnish is used

.github/workflows/browser-tests.yml
JIRA: https://issues.ibexa.co/browse/IBX-2317
Requires: https://github.com/ibexa/ci-scripts/pull/53
This PR adds support for running tests on stable tags - there's a new script in ci-scripts that takes care of that.
=> [Browser tests] Added support for setting up releases

.github/workflows/browser-tests.yml
Increased job maximum timeout to 60 minutes.
Value is changed globally.
Previous value of 30 minutes was causing timeouts. Already in some repos custom values were applied, e.g. 40 minutes in admin-ui.
=> [Browser tests] Increased job maximum timeout to 60 minutes

.github/workflows/browser-tests.yml
With the current order (input first, groups second) it's not possible to override the values.
The proposed order makes it possible to specify something like:
`--profile=regression --suite=experience --group-count=4 --group-offset=3`
in a PR, which will run only a subset of tests.
This can be useful for debugging, as it allows to run a specific group on CI.
Tested in https://github.com/ibexa/page-builder/pull/180/commits/d43a4a58e5d13bcfbcedabb53cde45a3b482c65e
With build: https://github.com/ibexa/page-builder/actions/runs/3620877907/jobs/6103639775
=> Allow overriding group and group offset

.github/workflows/browser-tests.yml
This will switch the browser tests from TRAVIS_GITHUB_TOKEN to using GH Application token, as per https://ibexa.atlassian.net/wiki/spaces/ENG/pages/12713999/Migrating+from+TRAVIS+GITHUB+TOKEN.
Note: the callee workflow must be updated by adding the following 3 lines to secrets:
```
AUTOMATION_CLIENT_ID: ${{ secrets.AUTOMATION_CLIENT_ID }}
AUTOMATION_CLIENT_INSTALLATION: ${{ secrets.AUTOMATION_CLIENT_INSTALLATION }}
AUTOMATION_CLIENT_SECRET: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
```
As of this moment, necessary secrets have been created only in the ibexa organization, not ezsystems. TBF
=> Enable browser test workflow to use GH App token

.github/workflows/browser-tests.yml
After https://github.com/ibexa/gh-workflows/pull/30 we are working with higher Github API limits, which means we can enable test sharding in PR builds as well.
Tested in:
https://github.com/ibexa/commerce/pull/205
https://github.com/ibexa/commerce/actions/runs/4007016570/jobs/6879296836
Result: build time decreases from 2h to 30 min
=> [Browser tests] Enabled test sharding for PR builds

.github/workflows/browser-tests.yml
Right now our compatibility-layer installation happens without access to Composer cache, see for example:
https://github.com/ibexa/oss/actions/runs/4098624088/jobs/7067870397
```
Run cd ${HOME}/build/project
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Info from [https://repo.packagist.org:](https://repo.packagist.org/) #StandWithUkraine
./composer.json has been updated
Running composer update ibexa/compatibility-layer
Loading composer repositories with package information
Cannot create cache directory /root/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Info from [https://repo.packagist.org:](https://repo.packagist.org/) …
```
=> [Browser tests] Enabled Composer cache when installing compatibility-layer

.github/workflows/browser-tests.yml
Things done:
1) `project-version` input is now optional - if not passed it will be taken directly from the branch-alias defined in composer.json.
Example: https://github.com/ibexa/admin-ui/blob/main/composer.json#L82
This makes the maintenece much easier, because we won't have to update values when creating stable branches (https://github.com/ibexa/admin-ui/blob/main/.github/workflows/browser-tests.yaml#L16)
2) https://github.com/ibexa/gh-workflows/pull/31 was a step in the right direction, but missed that the higher limits are not available for v3 - and we should not introduce that for v3 version.
I'm bringing it back, only for v3 (where we will still be passing the `project-version` input)
Tested in https://github.com/ibexa/behat/pull/54
=> Made project version optional

.github/workflows/browser-tests.yml
To avoid hitting GitHub API limits we need to find the sweet spot for the number of jobs running the tests - I've seen Github Api limit exceeded last week (on Tuesday), this PR changes the logic to limit the number of jobs for v4 PRs.
> **Note**
> The new logic looks like this:
|Version|Is a Pull Request|Job Count in config|Result|Comment|
|---|---|---|---|---|
|v3| No| 4|4| Non-PR runs: the job number from config is taken|
|v4| No| 4|4| Non-PR runs: the job number from config is taken|
|v3| Yes| 3|1| v3 PR runs: the job number is always 1|
|v4| Yes| 4|3| v4 PR runs: the job number is capped at 3|
|v4| Yes| 2|2| v4 PR runs: the job number is capped at 3|
Tested in https://github.com/ibexa/commerce/pull/218
Why 3? Well, I don't have the data to back it up - right now some jobs are running …
=> [Browser tests] Limited job-count for v4 to 3

.github/workflows/browser-tests.yml, .github/workflows/cross-merge.yml
https://issues.ibexa.co/browse/IBX-5077
Github Actions has deprecated the set-output and save-state functions:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> IBX-5077: Changed deprecated GitHub actions and variable name change for consistency

.github/workflows/browser-tests.yml
Small follow-up to get rid of the last deprecation notice:
https://github.com/ibexa/admin-ui/actions/runs/4371651951
It's no triggered on PR runs, that's why we didn't catch it.
=> [CI] Bumped Slack action version

.github/workflows/release_bundle.yml
This reusable workflow is to replace the one hard-coded in repositories for bundles.
Like ibexa/admin-ui, product-catalog etc.
It is supposed to be called like this:
```
name: Call Automatic Changelog Generator for tag Workflow
on:  
push:
tags:
- 'v*'
- '!v*-alpha*'
jobs:
create_release_for_tag:
uses: ibexa/gh-workflows/.github/workflows/release_bundle.yml@main
secrets:
JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
```
That way "when to run" is on the repository side, but "what to run" is externalized.
=> IBX-5533: Reusable changelog workflow for bundles

.github/workflows/browser-tests.yml
The automatic version detection is based on the value present in composer.json.
For 3.3 it detects `3.3.x-dev`, but our script for that version in `ci-scripts` is called `^3.3.x-dev` - it's not worth changing everything for 3.3 to fix that, so this workaround is enough to have working automatic version detection for 3.3.
It's needed for:
https://github.com/ibexa/oss/pull/105
=> Added workaround for 3.3.x-dev version detection

.github/workflows/browser-tests.yml
**JIRA**: [IBX-6383](https://issues.ibexa.co/browse/IBX-6383)
The goal of the task is to remove the whole Allure reports integration from our test code in order to shut the server hosting it down.
Complementary to: https://github.com/ezsystems/BehatBundle/pull/293
=> IBX-6383: Remove Allure reports integration from CI

.github/workflows/browser-tests.yml
This sets error reporting:
```
error_reporting = E_ALL & ~E_DEPRECATED
```
for PHP 8.0+.
Requires: https://github.com/ibexa/docker/pull/18
Tested in: https://github.com/ezsystems/BehatBundle/pull/294
=> Set error reporting to E_ALL&~E_DEPRECATED for PHP 8

.github/workflows/browser-tests.yml
This approach did not work, replaced by https://github.com/ibexa/ci-scripts/pull/80
It didn't work because Symfony sets the error reporting level to all in debug mode - and ignores the original setting.
=> [Browser tests] Removed setting error reporting for PHP 8.2

.github/workflows/browser-tests.yml
**JIRA:** https://issues.ibexa.co/browse/IBX-6507
Before multi repo setup did not take into account the type of search engine.
Now setup is divided into three: for Solr, for Elastic and for Legacy (SQL) Search Engine.
Companion PR: https://github.com/ibexa/behat/pull/108
=> IBX-6507: Separated multi repository setups depending on search engine

.github/workflows/browser-tests.yml
| :ticket: Issue | IBX-XXXXX |
- https://github.com/ibexa/ci-scripts/pull/86
Docker compose v1 is being removed from Ubuntu images on GitHub Actions, ref. https://github.com/actions/runner-images/issues/9557. 
It started on April 1 and it will take a few days to complete the rollout process. That's why now some jobs work (using older images) and some don't (using newer images).
We need to migrate in our scripts from using docker compose v1 to docker compose v2, ref. https://docs.docker.com/compose/migrate/.
Example failure:
`./prepare_project_edition.sh: line 152: docker-compose: command not found`
ref. https://github.com/ibexa/oss/actions/runs/8529904557/job/23366655720.
Example failing image: 
20240401.4.0.
Example working image:
20240324.2.0.
=> Migrate to Compose V2

.github/workflows/browser-tests.yml
| :ticket: Issue | IBX-XXXXX |
To unblock work on setting PHP 8.3 as minimum and default for v5.
=> Bump default image to PHP 8.3

.github/workflows/browser-tests.yml
> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
> - [x] :exclamation:  **Remove TMP commits before merge** :exclamation:
| :ticket: Issue | IBX-8470 |
This PR bumps Symfony to v6 with codebase upgrades.
Key changes:
N/A
N/A
=> IBX-8470: Upgraded codebase to Symfony 6

.github/workflows/rector.yml
| :ticket: Issue | IBX-9627 |
|----------------|--------|
- https://github.com/ibexa/rector/pull/24
Usage in packages' GHA CI configuration:
```yaml
jobs:
rector:
name: Run rector
uses: ibexa/gh-workflows/.github/workflows/rector.yml@main
```
For closed-source packages that are required during composer install, you need to additionally pass Satis secrets, so the config would look like:
```yaml
jobs:
rector:
name: Run rector
uses: ibexa/gh-workflows/.github/workflows/rector.yml@main
secrets:
SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
```
`ibexa/rector:~5.0.x-dev` or `~4.6.x-dev` dependency needs to be added to each package's `composer.json`, along with generic …
=> IBX-9627: [GHA] Created Rector PHP reusable workflow

.github/workflows/browser-tests.yml
| :ticket: Issue | IBX-XXXXX |
Added slack notifications to `monitoring-github-ci` channel for setup jobs also. Previously only browser tests jobs were covered.
Rationale: Sometimes in nightly regressions some builds fail on setup jobs level. Such failures are not visible on the slack channel. With this change it will be easier to spot them.
Notifications for setup jobs are only allowed for failure or cancelled job statuses.
Example test success notification from below test PR (served only as confirmation it works):
ref. https://ibexa.slack.com/archives/C06GUKQSMPB/p1741356986934899
Tested in https://github.com/ibexa/oss/pull/207.
=> [Browser tests] Added slack notifications for setup jobs

.github/workflows/browser-tests.yml
| :ticket: Issue | IBX-8471 |
- https://github.com/ibexa/http-cache/pull/68
- https://github.com/ibexa/recipes-dev/pull/175
- https://github.com/ibexa/docker/pull/40
Alternative to https://github.com/ibexa/recipes-dev/pull/175. Added `APP_SECRET` to GHA job env variables instead of installing it through recipes. Requires https://github.com/ibexa/docker/pull/40.
See https://github.com/ibexa/recipes-dev/pull/175 for more details on the issue at hand.
=> IBX-8471: [Browser tests] Configured `APP_SECRET` for Behat tests

.github/workflows/browser-tests.yml
| :ticket: Issue | IBX-8471 |
|----------------|-----------------------|
- #61
Looks like [`APP_SECRET` needs to be longer for JWT to work properly](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1063#issuecomment-1229897168).
Too short `APP_SECRET` causes [this PB issue](https://github.com/ibexa/page-builder/actions/runs/15067260858/job/42354807284#step:18:93).
My local tests show that 32 characters is enough [1], but following the issue linked above, I've made it 64 just to be safe.
[1] That's why I couldn't reproduce it locally.
Occurs only for regression tests setup.
=> IBX-8471: [Browser tests] Made `APP_SECRET` longer for JWT

.github/workflows/browser-tests.yml
| :ticket: Issue | IBX-9916 |
Bumping default image to PHP 8.3 & Node 22
Changing Node version only here. Needed for the sake of 5.0 after CKE 45 merge.
=> Bump default image to PHP 8.3 & Node 22
